# Use the official Nginx image from Docker Hub
FROM nginx:latest

# Copy your custom Nginx configuration file to the container
COPY nginx.conf /etc/nginx/nginx.conf

# If you have static files, uncomment and use the following line to copy them to Nginx's default directory
# COPY ./dist /usr/share/nginx/html

# Expose port 80 to allow traffic to the Nginx server
EXPOSE 80


