# Use the official Node.js image
FROM node:14

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json first
COPY app/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application source code
COPY app .

# Expose port 3000
EXPOSE 3000

# Command to run the application
CMD ["npm", "start"]


